# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-17 17:53
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import userarea.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userarea', '0002_facebookmessage_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='/static/img/avatar.png', null=True, upload_to=userarea.models.custom_user_directory_path)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
