# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-18 23:15
from __future__ import unicode_literals

from django.db import migrations, models
import userarea.models


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0003_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facebookaccount',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(blank=True, default='/pictures/avatar.png', null=True, upload_to=userarea.models.custom_user_directory_path),
        ),
        migrations.AlterField(
            model_name='facebookprofileurl',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
