# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-19 23:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0004_auto_20180218_2315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facebookprofileurl',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='facebookaccount',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
