# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 00:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0005_auto_20180219_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facebookaccount',
            old_name='password',
            new_name='fb_pass',
        ),
        migrations.RenameField(
            model_name='facebookaccount',
            old_name='username',
            new_name='fb_user',
        ),
    ]
