# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 03:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0007_auto_20180220_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='created_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
