# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-23 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0009_facebookprofileurl_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facebookprofileurl',
            options={'ordering': ['id']},
        ),
    ]
