# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-25 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0014_collectprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookprofileurl',
            name='full_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
