# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0015_facebookprofileurl_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectprogress',
            name='url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
