# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 15:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0010_connect'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userarea', '0016_collectprogress_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_limit', models.IntegerField()),
                ('stripe_plan', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pinax_stripe.Plan')),
            ],
        ),
        migrations.CreateModel(
            name='UserPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages_sent', models.IntegerField(default=0)),
                ('stripe_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pinax_stripe.Plan')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
