# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 15:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0017_defaultplan_userplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplan',
            name='created_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
