# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0019_defaultplan_box_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultplan',
            name='box_color',
            field=models.CharField(blank=True, choices=[('g', 'green'), ('y', 'yellow'), ('p', 'purple')], default='y', max_length=1, null=True),
        ),
    ]
