# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0020_auto_20180304_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplan',
            name='messages_sent',
            field=models.IntegerField(default=100),
        ),
    ]
