# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-18 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0023_facebookprofileurl_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatus',
            name='message',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
