# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-18 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0024_taskstatus_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookprofileurl',
            name='task_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
