# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0025_auto_20180318_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatus',
            name='url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
