# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0026_taskstatus_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatus',
            name='tag',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
