# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 14:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0027_taskstatus_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookprofileurl',
            name='updated_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
